# -*- coding: utf-8 -*-
"""project aircompressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgwRxgfxbqPwGkYznGAdVx21EncVEIKE
"""

# =========================================================
# 1. INSTALL REQUIRED PACKAGES
# =========================================================
!pip install librosa tqdm -q
# =========================================================
# 2. IMPORT LIBRARIES
# =========================================================
import os
import requests
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import layers

# =========================================================
# 3. GITHUB REPOSITORY SETTINGS
# =========================================================
# GitHub API path to your Audio folder
BASE_API = "https://api.github.com/repos/kingofrichnight/Air-compressor-sound-monitoring-system/contents/Audio"

# Folder mapping: label -> GitHub folder name
folders = {
    "Off": "Off",
    "Rest": "Rest",
    "Run": "Run"
}

# Local download folder in Colab
DOWNLOAD_PATH = "dataset"
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

# =========================================================
# 4. DOWNLOAD ALL WAV FILES FROM EACH GITHUB FOLDER
# =========================================================
def download_folder_from_github(folder_name, label_name):
    """
    Downloads all .wav files from a GitHub folder using GitHub Contents API.
    """
    url = f"{BASE_API}/{folder_name}"
    response = requests.get(url)

    if response.status_code != 200:
        print(f"Failed to access folder: {folder_name}")
        print("Status code:", response.status_code)
        print("Response:", response.text)
        return

    files = response.json()
    save_dir = os.path.join(DOWNLOAD_PATH, label_name)
    os.makedirs(save_dir, exist_ok=True)

    wav_count = 0
    for file in tqdm(files, desc=f"Downloading {label_name}"):
        if isinstance(file, dict) and file.get("name", "").lower().endswith(".wav"):
            download_url = file.get("download_url")
            file_path = os.path.join(save_dir, file["name"])

            r = requests.get(download_url)
            if r.status_code == 200:
                with open(file_path, "wb") as f:
                    f.write(r.content)
                wav_count += 1

    print(f"{label_name}: downloaded {wav_count} wav files")


# Download all folders
for label_name, folder_name in folders.items():
    download_folder_from_github(folder_name, label_name)

# =========================================================
# 5. CHECK DOWNLOADED FILES
# =========================================================
for label in os.listdir(DOWNLOAD_PATH):
    label_path = os.path.join(DOWNLOAD_PATH, label)
    if os.path.isdir(label_path):
        wav_files = [f for f in os.listdir(label_path) if f.lower().endswith(".wav")]
        print(f"{label}: {len(wav_files)} files")

# =========================================================
# 6. AUDIO / FEATURE EXTRACTION PARAMETERS
# =========================================================
SR = 48000            # Sampling rate
N_FFT = 2048          # FFT size
HOP_LENGTH = N_FFT // 4
N_MELS = 128

# MTConnect-style window setup
n_chunk = 2048
n_seq = 23
n_interval = 2048
window_size = n_chunk * n_seq   # 2048 * 23 = 47104 samples (~0.98 sec)

print("Window size in samples:", window_size)
print("Window size in seconds:", window_size / SR)

# =========================================================
# 7. OPTIONAL: VISUALIZE ONE EXAMPLE FILE
# =========================================================
def plot_wave_and_mel(file_path, title_text="Audio"):
    y, sr = librosa.load(file_path, sr=SR)

    mel = librosa.feature.melspectrogram(
        y=y, sr=sr,
        n_fft=N_FFT,
        hop_length=HOP_LENGTH,
        win_length=N_FFT,
        window='hann',
        n_mels=N_MELS
    )

    fig, ax = plt.subplots(1, 2, figsize=(15, 4))

    librosa.display.waveshow(y, sr=sr, ax=ax[0])
    ax[0].set_title(f"{title_text}: Time Domain")
    ax[0].set_xlabel("Time [sec]")
    ax[0].set_ylabel("Amplitude")
    ax[0].set_ylim([-1, 1])

    img = librosa.display.specshow(
        librosa.power_to_db(2 * np.abs(mel) / N_FFT, ref=1),
        ax=ax[1],
        x_axis='time',
        y_axis='mel',
        sr=sr,
        vmin=-80,
        vmax=0
    )
    ax[1].set_title(f"{title_text}: Mel-Spectrogram")
    ax[1].set_xlabel("Time [sec]")
    ax[1].set_ylabel("Mel Frequency")

    fig.colorbar(img, ax=ax[1], format="%+2.0f dB")
    plt.tight_layout()
    plt.show()

# =========================================================
# 8. PLOT FIRST 2 FILES FROM EACH CLASS
# =========================================================
NUM_FILES = 2

for label in ["Off", "Rest", "Run"]:
    folder = os.path.join(DOWNLOAD_PATH, label)

    if not os.path.exists(folder):
        continue

    wav_files = [f for f in os.listdir(folder) if f.lower().endswith(".wav")]

    print(f"\n===== {label} =====")
    for file in wav_files[:NUM_FILES]:
        file_path = os.path.join(folder, file)
        plot_wave_and_mel(file_path, title_text=f"{label} - {file}")

# =========================================================
# 9. FUNCTION TO EXTRACT MEL-SPECTROGRAM WINDOWS
# =========================================================
def extract_windows_from_audio(y, label):
    X = []
    Y = []

    total_len = len(y)

    if total_len < window_size:
        return [], []

    for start in range(0, total_len - window_size + 1, n_interval):
        segment = y[start:start + window_size]

        mel = librosa.feature.melspectrogram(
            y=segment,
            sr=SR,
            n_fft=N_FFT,
            hop_length=HOP_LENGTH,
            win_length=N_FFT,
            window='hann',
            n_mels=N_MELS
        )

        feature = 2 * np.abs(mel) / N_FFT
        X.append(feature.astype(np.float32))
        Y.append(label)

    return X, Y

# =========================================================
# 10. BUILD DATASET FROM ALL FILES
# =========================================================
X_data = []
Y_data = []

for label in os.listdir(DOWNLOAD_PATH):
    label_path = os.path.join(DOWNLOAD_PATH, label)

    if not os.path.isdir(label_path):
        continue

    wav_files = [f for f in os.listdir(label_path) if f.lower().endswith(".wav")]

    for wav_file in tqdm(wav_files, desc=f"Processing {label}"):
        file_path = os.path.join(label_path, wav_file)

        try:
            y, sr = librosa.load(file_path, sr=SR)
            X_temp, Y_temp = extract_windows_from_audio(y, label)
            X_data.extend(X_temp)
            Y_data.extend(Y_temp)

        except Exception as e:
            print(f"Error processing {file_path}: {e}")

X_data = np.array(X_data)
Y_data = np.array(Y_data)

print("X_data shape:", X_data.shape)
print("Y_data shape:", Y_data.shape)

# =========================================================
# 11. CHECK LABEL DISTRIBUTION
# =========================================================
plt.figure(figsize=(6, 4))
ax = sns.countplot(x=Y_data)
plt.title("Label Frequency")
plt.xlabel("Class")
plt.ylabel("Count")

for container in ax.containers:
    ax.bar_label(container)

plt.show()

# =========================================================
# 12. ENCODE LABELS
# =========================================================
enc = LabelEncoder()
Y_encoded = enc.fit_transform(Y_data)
Y_label = to_categorical(Y_encoded)

print("Classes:", enc.classes_)
print("Encoded label shape:", Y_label.shape)

# =========================================================
# 13. TRAIN / TEST SPLIT
# =========================================================
X_train, X_test, Y_train, Y_test = train_test_split(
    X_data,
    Y_label,
    test_size=0.2,
    random_state=42,
    stratify=Y_encoded
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

# =========================================================
# 14. BUILD CNN MODEL
# =========================================================
model = tf.keras.Sequential([
    layers.Reshape((X_train.shape[1], X_train.shape[2], 1), input_shape=(X_train.shape[1], X_train.shape[2])),

    layers.Conv2D(8, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(16, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(Y_train.shape[1], activation='softmax')
])

model.summary()

# =========================================================
# 15. COMPILE MODEL
# =========================================================
BATCH_SIZE = 128
EPOCHS = 10
LEARNING_RATE = 1e-3

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# =========================================================
# 16. TRAIN MODEL
# =========================================================
history = model.fit(
    X_train,
    Y_train,
    validation_data=(X_test, Y_test),
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    verbose=1
)

# =========================================================
# 17. PLOT TRAINING HISTORY
# =========================================================
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='train_accuracy')
plt.plot(history.history['val_accuracy'], label='val_accuracy')
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.legend()

plt.tight_layout()
plt.show()

# =========================================================
# 18. EVALUATE MODEL
# =========================================================
Y_pred_prob = model.predict(X_test)
Y_pred = np.argmax(Y_pred_prob, axis=1)
Y_true = np.argmax(Y_test, axis=1)

acc = accuracy_score(Y_true, Y_pred)
prec = precision_score(Y_true, Y_pred, average='weighted')
rec = recall_score(Y_true, Y_pred, average='weighted')
f1 = f1_score(Y_true, Y_pred, average='weighted')

print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"F1 Score  : {f1:.4f}")

# =========================================================
# 19. CLASSIFICATION REPORT
# =========================================================
print(classification_report(Y_true, Y_pred, target_names=enc.classes_))

# =========================================================
# 20. CONFUSION MATRIX
# =========================================================
cm = confusion_matrix(Y_true, Y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=enc.classes_,
    yticklabels=enc.classes_
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

# =========================================================
# 21. SAVE MODEL
# =========================================================
model.save("air_compressor_cnn.h5")
print("Model saved as air_compressor_cnn.h5")